project:
  type: website

website:
  title: "website 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: llaclass.qmd
        text: LLA Class

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
